config/routes.rb
Rails.application.routes.draw do

  # get 'homes/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index, :show, :edit, :update]

  get '/search', to: "bookings#search"

  # get '/error', to: "flights#error"

  root to: 'pages#home'
  resources :airports  do 
    resources :airlines
  end
  resources :flights

  resources :schedules

  resources :tickets

  resources :bookings 

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  # resources :airlines, only: [:index,:show,:create,:new] do 
  #     resources :flights
  # end
   

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airline
  has_many :schedules,dependent: :destroy
  has_many :tickets,dependent: :destroy

  validates :name,:source,:destination, presence: true

  after_create :check_length_of_name



    private

    def check_length_of_name
      if self.name.length >= 6
        self.name =  name
      else
        self.name = "Length is less than 6"
      end
    end

    def self.search_by(search_term)
        where("LOWER(name) LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) LIKE :search", search: "%#{search_term.downcase}%")
    end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index] 
  # before_action :index, only: [:show]
  # load_and_authorize_resource
  # before_action :is_admin?, only: [:show, :index]
  def new 
    @flight = Flight.new

    respond_to do |format|
      format.html
      format.js
    end
  end

  def index 
    @flights = Flight.all
    
    if params[:search]
      @search = params[:search]
      @flights = @flights.search_by(@search)
    else
      @flights = Flight.all
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  def create
    @flight = Flight.create(flight_params)
      respond_to do |format|
        if @flight.save
          format.html { redirect_to @flight, notice: "Flight was successfully created." }
          format.js
        else
          render 'new' 
        end
      end
  end
        
  def edit
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html 
      format.js
    end
  end

  def update
    @flight = Flight.find(params[:id])
    respond_to do |format|
    if @flight.update(flight_params)
      format.html { redirect_to flights_path }

      format.js
    else
      format.js { render 'edit' }
    end
    end
  end

  def show
    @flight = Flight.find(params[:id])

    respond_to do |format|
      format.html
      format.js
    end
  end

  def destroy
    @flight = Flight.find(params[:id])
    @flight.destroy

    respond_to do |format|
      redirect_to flights_path
      format.js
    end
  end

  private
  # def set_airline
 #      @airline = Airline.find(params[:airline_id])
  # end
  # def is_admin?
 #      current_user.role.code == 'employee'
 #    end

  def flight_params
    params.require(:flight).permit(:name,:source,:destination,:status,:airline_id)
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/flights/_form.html.erb
<% if current_user.role.code == "admin" %>
<%= form_with(model: @flight) do |form| %>

<!-- Validations Section -->
 <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@flight.errors.count, "error") %> prohibited
        this Flight from being saved:
      </h2>
      <ul>
        <% @airline.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Validation Section Ends Here -->

    <!-- Add Data -->
 <p>
  <%= form.label :name %><br />
  <%= form.text_field :name, class: "form-control", placeholder: "Flight Name" %>
</p>


 <p>
  <%= form.label :source %><br />
  <%= form.text_field :source, class: "form-control", placeholder: "Source" %>
</p>

<p>
  <%= form.label :destination %><br />
  <%= form.text_field :destination, class: "form-control", placeholder: "Destination" %>
</p>

<p>
  <%= form.label :status %><br />
  <%= form.text_field :status, class: "form-control", placeholder: "Status" %>
</p>

<p>
  <%= form.label :airline_id %><br />
  <%= form.select :airline_id, Airline.all.collect { |a| [ a.name, a.id ]  } %>
</p>

<p>
	<%= form.submit class: "btn btn-outline-success" %>
</p>

<% end %>

<% end %>

app/views/flights/edit.html.erb
<% if current_user.role.code == "admin" %>
<div class="container">
    <div class="row">
       <div class="col-8">
           <h3>Edit Flight Details</h3>
<div id = "form">
 <%= render 'form' %>
 
 <%= link_to 'Back', flights_path, class: "btn btn-dark" %>
</div>

       </div> 
    </div>
</div>
<% else %>
<%= render 'layouts/alerts' %>
<% end %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="row">
		<div class="col-8">
			<h3>Flight List</h3>
			<% if user_signed_in? && current_user.role.code == "admin" %>
<%= link_to 'Add Flights', new_flight_path,class: "btn btn-outline-primary btn-sm"%> &nbsp;&nbsp;
<!-- ,data: { bs_toggle: 'modal' , bs_target: '#addFlightModal' , remote: true} -->

<%= link_to 'Add Schedules', new_schedule_path, class: "btn btn-outline-primary btn-sm"  %>
<% end %>

<br><br>
<%= form_for "",url: flights_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term, placeholder: "Search..",class: "form-control" %>
<% end %>
<br>
<table class="table table-striped table-hover table-bordered">
	<tr>
	<th>Flight Name</th>
	<th>Source</th>
	<th>Destination</th>	
	<th>Status</th>
	<th colspan="3">Actions</th>
	</tr>
<% @flights.each do |flight| %>
	<tr id= "dom_id">
		<td><%= flight.name %></td>
		<td><%= flight.source %></td>
		<td><%= flight.destination %></td>
		<td><%= flight.status %></td>
		
		<td><%= link_to 'Show',flight_path(flight), class: "btn btn-outline-info btn-sm" %></td>
	
		<% if user_signed_in? && current_user.role.code == "admin" %>
		
		<td><%= link_to 'Edit',edit_flight_path(flight), remote: true, class: "btn btn-outline-warning btn-sm" %></td>
		<td><%= link_to 'Delete',flight_path(flight), class: "btn btn-outline-danger btn-sm" ,
		method: :delete, remote: true, data: { confirm: "Are you Sure? " } %></td>
<% else %>
		<td><%= link_to 'Book a Flight',new_booking_path, class: "btn btn-outline-info btn-sm" %>
	
		</td>
	
		<% end %>
	</tr>
<% end %>
</table>
		</div>
	</div>
</div>


<!-- Modal -->
<!-- <div class="modal fade" id="addFlightModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Modal title</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div> -->

app/views/flights/new.html.erb
<% if current_user.role.code == "admin" %>
<div class="container">
    <div class="row">
       <div class="col-8">
           <h3>Add a Flight Details</h3>
<div id = "form">
   <%= render 'form' %>
 
 <%= link_to 'Back', flights_path, class: "btn btn-dark" %>
 
</div>
 
       </div> 
    </div>
</div>
<% else %>
<%= render 'layouts/alerts' %>
<% end %>

app/views/flights/show.html.erb
<div class="container">
	<div class="row">
	  <div class="text-center">
	  		<div class="col-md-6">
			<div class="card text-center">
  <div class="card-header">
    <strong>Flight Details</strong>
  </div>
  <div class="card-body">
    <table class="table">
       <tr>
       	<th class="card-title">Flight Name</th>
        <th class="card-title">From: </th>
        <th class="card-title">To: </th>
        <th class="card-title">Status</th>
        <th class="card-title">Airline</th>
       </tr>
      <tr>
      	<td class="card-text"><%= @flight.name %></td>
      	<td class="card-text"><%= @flight.source %></td>
      	<td class="card-text"><%= @flight.destination %></td>
      	<td class="card-text"><%= @flight.status %></td>
      	<td class="card-text"><%= @flight.airline_id %></td> 
      </tr>
    </table>
  </div>
 
  <div class="card-footer text-muted">
    <% if user_signed_in? && current_user.role.code == "admin" %>
    <%= link_to 'Edit', edit_flight_path(@flight), class: "btn btn-success" %>
    <% end %>
	<%= link_to 'Back', flights_path, class: "btn btn-dark" %>
  </div>
</div>
		</div>	
	  </div>
	</div>	
</div>