config/routes.rb
Rails.application.routes.draw do

  # get 'homes/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index, :show, :edit, :update]

  get '/search', to: "bookings#search"

  # get '/error', to: "flights#error"

  root to: 'pages#home'
  resources :airports  do 
    resources :airlines
  end
  resources :flights

  resources :schedules

  resources :tickets

  resources :bookings 

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  # resources :airlines, only: [:index,:show,:create,:new] do 
  #     resources :flights
  # end
   

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
  #   if user.role.code == "admin"
  #     can :manage, :all
  #   elsif user.role.code == "employee"
  #       # can :read, Schedule
  #       # can :read, Flight
  #       # can :read, Booking
  #       can :update, Booking, user_id: user.id
  #       can :read, Ticket
  #     end
   end
end

app/models/airline.rb
class Airline < ApplicationRecord
	belongs_to :airport
	has_many :flights,dependent: :destroy
    
    validates :name, presence: true, uniqueness: { message: " this Airline is already registered with this airport " }
	validates :airline_type, inclusion: { in: %w( National International national international) }
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :users
	has_many :airlines,dependent: :destroy

	validates :airport_name, length: { minimum: 6 },uniqueness: { message: "Already exists..." }
	# validates :country , inclusion: { in: %w( India, US ), message: "%{value} is not a valid Country." }
	# validates :state, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
	# validates :city, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	# Associations
	belongs_to :ticket
	belongs_to :user

	# Validations

	validates :ticket_id, uniqueness: { message: " currently not available try again later." }
	validates :name_of_passenger,:source,:destination,presence: true, length: { minimum: 3 }
	validates_each :name_of_passenger, :source, :destination do |record, attr, value|
        record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
    end
    validates :age, presence:true, numericality: { only_integer: true }
    validates :phone, presence:true,numericality: { only_integer: true }, length: { is: 10 }
    validates :address,presence:true, length: { minimum: 6 }
    validates :email, presence: true, email:true
	# validates :passport_no, format: { with: /^[1-9]{1}[0-9]{2}\\s{0, 1}[0-9]{3}$/ }, :multiline => true  
    validates :passport_no, presence: true
	
    # CallBacks
	after_create :welcome_email

	# before_save :check_passport_length

	before_create :view_premissions
	
    # methods
	private
	def welcome_email
		BookingMailer.welcome_email(self.email).deliver_now
	end 

	def check_passport_length
		if passport_no.length == 8
			# byebug
			self.passport_no = passport_no
		else 
			self.passport_no = "Invalid Passport"
		end
	end

	def self.search_by(search_term)
        where("LOWER(name_of_passenger) LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) OR LOWER(class_type) LIKE :search ", search: "%#{search_term.downcase}%")
    end

    def self.view_premissions(current_user)
  		current_user.role.code == "admin"? Booking.all : current_user.bookings
	end

end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airline
  has_many :schedules,dependent: :destroy
  has_many :tickets,dependent: :destroy

  validates :name,:source,:destination, presence: true

  after_create :check_length_of_name



    private

    def check_length_of_name
      if self.name.length >= 6
        self.name =  name
      else
        self.name = "Length is less than 6"
      end
    end

    def self.search_by(search_term)
        where("LOWER(name) LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) LIKE :search", search: "%#{search_term.downcase}%")
    end
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users,dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	belongs_to :flight

	validates :d_time,:a_time,:duration,presence: true 

	def self.search_by(search_term)
        where("flight_id LIKE :search ", search: "%#{search_term.downcase}%")
    end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :flight
	
	has_one :booking,dependent: :destroy

	# validates :passport_no, format: { with: /[A-PR-WYa-pr-wy][1-9]\\d\\s?\\d{4}[1-9]/ }
	validates :seatno, :class_type, :source, :destination, presence: true
	validates :class_type, inclusion: { in: %w(First Business Economy first business economy) }

	private
	def self.search_by(search_term)
        where("seatno LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) OR LOWER(class_type) LIKE :search  LIKE :search ", search: "%#{search_term.downcase}%")
    end

end

app/models/user.rb
class User < ApplicationRecord
belongs_to :airport
has_many :bookings,dependent: :destroy
has_many :tickets, dependent: :destroy
after_create :set_default_role
belongs_to :role, optional: true
has_one_attached :image
# has_one :flight
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  # enum role: [ employee: 0, admin: 1 ]

  validates :phone, numericality: { only_integer: true },length: { is:10 } 

  validates :name, presence: true, length: { minimum: 5 }

  validates :age, numericality: { only_integer: true }

  validates_each :name do |record, attr, value|
      record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

    def full_name
      "#{name} #{age}"
    end

    private 
    def set_default_role
      self.update(role_id: Role.find_by(code: 'employee').id)
    end
    
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
    # load_and_authorize_resource
	def new
        @schedule = Schedule.new
    end

    def index
        @schedules = Schedule.all
        if params[:search]
            @search = params[:search]
            @schedules = @schedules.search_by(@search)
        else
            @schedules = Schedule.all
        end
    end

    def create
        @schedule = Schedule.create(schedule_params)
        if @schedule.save
            redirect_to schedule_path(@schedule)
        else
            render 'new'
        end
    end

    def show
        @schedule = Schedule.find(params[:id])
    end

    def edit
        @schedule = Schedule.find(params[:id])
    end

    def update
        @schedule = Schedule.find(params[:id])

    if @schedule.update(schedule_params)
        redirect_to @schedule
    else
        render 'edit'
    end
    end

    def destroy
        @schedule = Schedule.find(params[:id])

        @schedule.destroy
        redirect_to schedules_path
    end

    private
    
    def schedule_params
        params.require(:schedule).permit(:d_time,:a_time,:duration, :flight_id)
    end

end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/schedules/_form.html.erb
<%= form_with model: @schedule,local: true do |form| %>
 <!-- Validations Section -->
 <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@schedule.errors.count, "error") %> prohibited
        this schedule from being saved:
      </h2>
      <ul>
        <% @schedule.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <!-- Validation Section Ends Here -->

  <!-- Add Data -->
<p>
  <%= form.label :DepartureTime %><br />
  <%= form.datetime_select :d_time, class: "form-select" %>
</p>


 <p>
  <%= form.label :Arrival_Time %><br />
  <%= form.datetime_select :a_time , class: "form-select" %>
</p>


 <p>
  <%= form.label :duration %><br />
  <%= form.text_field :duration, class: "form-control" %>
</p>

 <p>
  <%= form.label :flight_id %><br />
  <%= form.select :flight_id, Flight.all.collect { |f| [ f.name , f.id ]  } %>
</p>


<p>
	<%= form.submit class: "btn btn-outline-success" %>
</p>

<% end %>

app/views/schedules/edit.html.erb
<% if current_user.role.code == "admin" %>
<div class="container">
    <div class="row">
       <div class="col-8">
           <h3>Edit Schedule</h3>

 <%= render 'form' %>
 
 <%= link_to 'Back', schedules_path, class: "btn btn-dark" %>

       </div> 
    </div>
</div>

<% else %>
<%= render 'layouts/alerts' %>
<% end %>

app/views/schedules/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-10">
      <h3>Schedule Details</h3>
  <% if user_signed_in?  && current_user.role.code == "admin" %>
<%= link_to 'Add Schedules', new_schedule_path, class: "btn btn-outline-primary btn-sm" %>
<% end %> <br><br>

<%= form_for "",url: schedules_path, role: "search", method: :get do %>
  <%= text_field_tag :search, @search_term, placeholder: "Search..",class: "form-control" %>
<% end %>
<br><br>  

<table class="table table-striped table-hover table-bordered">
  <tr>
    <th>Departure Time</th>
    <th>Arrival Time</th>
    <th>Duration</th>
    <th>Flight Id</th>
    <th colspan="3">Actions</th>
  </tr>
  <% @schedules.each do |sh| %>
  <tr>
    <td><%= sh.d_time  %></td>
    <td><%= sh.a_time  %></td>
    <td><%= sh.duration  %></td>
    <td><%= sh.flight_id  %></td>
    <td><%= link_to 'Show', schedule_path(sh), class: "btn btn-outline-info btn-sm" %></td>
    <% if user_signed_in? && current_user.role.code == "admin" %>
    <td><%= link_to 'Edit', edit_schedule_path(sh), class: "btn btn-outline-warning btn-sm"%></td>
    <td><%= link_to 'Delete', schedule_path(sh), class: "btn btn-outline-danger btn-sm", method: :delete, data: { confirm: "Are you Sure?? " } %>
    </td>
    <% end %>
  </tr>
 <% end %>
</table>
    </div>
  </div>
</div>

app/views/schedules/new.html.erb
<% if current_user.role.code == "admin" %>
 <div class="container">
    <div class="row">
       <div class="col-8">
           <h3>Add Schedules</h3>

 <%= render 'form' %>
 
 <%= link_to 'Back', schedules_path, class: "btn btn-dark" %>

       </div> 
    </div>
</div>

<% else %>
<%= render 'layouts/alerts' %>
<% end %>

app/views/schedules/show.html.erb
<div class="container">
	<div class="row">
	  <div class="text-center">
	  		<div class="col-md-8">
			<div class="card text-center">
  <div class="card-header">
    <strong>Schedule Details</strong>
  </div>
  <div class="card-body">
    <table class="table">
       <tr>
       	<th class="card-title">Departure Time</th>
        <th class="card-title">Arrival Time</th>
        <th class="card-title">Duration</th>
        <th class="card-title">Flight Id</th>
       </tr>
      <tr>
      	<td class="card-text"><%= @schedule.d_time %></td>
      	<td class="card-text"><%= @schedule.a_time %></td>
      	<td class="card-text"><%= @schedule.duration %></td>
      	<td class="card-text"><%= @schedule.flight_id %></td> 
      </tr>
    </table>
  </div>
  <div class="card-footer text-muted">
    <% if user_signed_in? && current_user.role.code == "admin" %>
    <%= link_to 'Edit', edit_schedule_path(@schedule), class: "btn btn-success" %>
    <% end %>
	  <%= link_to 'Back', schedules_path, class: "btn btn-dark" %>

  </div>
</div>
		</div>	
	  </div>
	</div>	
</div>