config/routes.rb
Rails.application.routes.draw do

  # get 'homes/index'
  devise_for :users
  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users, only: [:index, :show, :edit, :update]

  get '/search', to: "bookings#search"

  # get '/error', to: "flights#error"

  root to: 'pages#home'
  resources :airports  do 
    resources :airlines
  end
  resources :flights

  resources :schedules

  resources :tickets

  resources :bookings 

  # devise_scope :user do
  #   get '/users/sign_out' => 'devise/sessions#destroy'
  # end

  # resources :airlines, only: [:index,:show,:create,:new] do 
  #     resources :flights
  # end
   

 
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
 

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    
  #   if user.role.code == "admin"
  #     can :manage, :all
  #   elsif user.role.code == "employee"
  #       # can :read, Schedule
  #       # can :read, Flight
  #       # can :read, Booking
  #       can :update, Booking, user_id: user.id
  #       can :read, Ticket
  #     end
   end
end

app/models/airline.rb
class Airline < ApplicationRecord
	belongs_to :airport
	has_many :flights,dependent: :destroy
    
    validates :name, presence: true, uniqueness: { message: " this Airline is already registered with this airport " }
	validates :airline_type, inclusion: { in: %w( National International national international) }
end

app/models/airport.rb
class Airport < ApplicationRecord
	has_many :users
	has_many :airlines,dependent: :destroy

	validates :airport_name, length: { minimum: 6 },uniqueness: { message: "Already exists..." }
	# validates :country , inclusion: { in: %w( India, US ), message: "%{value} is not a valid Country." }
	# validates :state, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
	# validates :city, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	# Associations
	belongs_to :ticket
	belongs_to :user

	# Validations

	validates :ticket_id, uniqueness: { message: " currently not available try again later." }
	validates :name_of_passenger,:source,:destination,presence: true, length: { minimum: 3 }
	validates_each :name_of_passenger, :source, :destination do |record, attr, value|
        record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
    end
    validates :age, presence:true, numericality: { only_integer: true }
    validates :phone, presence:true,numericality: { only_integer: true }, length: { is: 10 }
    validates :address,presence:true, length: { minimum: 6 }
    validates :email, presence: true, email:true
	# validates :passport_no, format: { with: /^[1-9]{1}[0-9]{2}\\s{0, 1}[0-9]{3}$/ }, :multiline => true  
    validates :passport_no, presence: true
	
    # CallBacks
	after_create :welcome_email

	# before_save :check_passport_length

	before_create :view_premissions
	
    # methods
	private
	def welcome_email
		BookingMailer.welcome_email(self.email).deliver_now
	end 

	def check_passport_length
		if passport_no.length == 8
			# byebug
			self.passport_no = passport_no
		else 
			self.passport_no = "Invalid Passport"
		end
	end

	def self.search_by(search_term)
        where("LOWER(name_of_passenger) LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) OR LOWER(class_type) LIKE :search ", search: "%#{search_term.downcase}%")
    end

    def self.view_premissions(current_user)
  		current_user.role.code == "admin"? Booking.all : current_user.bookings
	end

end

app/models/email_validator.rb
class EmailValidator < ActiveModel::EachValidator
def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :airline
  has_many :schedules,dependent: :destroy
  has_many :tickets,dependent: :destroy

  validates :name,:source,:destination, presence: true

  after_create :check_length_of_name



    private

    def check_length_of_name
      if self.name.length >= 6
        self.name =  name
      else
        self.name = "Length is less than 6"
      end
    end

    def self.search_by(search_term)
        where("LOWER(name) LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) LIKE :search", search: "%#{search_term.downcase}%")
    end
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users,dependent: :destroy
end

app/models/schedule.rb
class Schedule < ApplicationRecord
	belongs_to :flight

	validates :d_time,:a_time,:duration,presence: true 

	def self.search_by(search_term)
        where("flight_id LIKE :search ", search: "%#{search_term.downcase}%")
    end
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :flight
	
	has_one :booking,dependent: :destroy

	# validates :passport_no, format: { with: /[A-PR-WYa-pr-wy][1-9]\\d\\s?\\d{4}[1-9]/ }
	validates :seatno, :class_type, :source, :destination, presence: true
	validates :class_type, inclusion: { in: %w(First Business Economy first business economy) }

	private
	def self.search_by(search_term)
        where("seatno LIKE :search OR LOWER(source) LIKE :search OR LOWER(destination) OR LOWER(class_type) LIKE :search  LIKE :search ", search: "%#{search_term.downcase}%")
    end

end

app/models/user.rb
class User < ApplicationRecord
belongs_to :airport
has_many :bookings,dependent: :destroy
has_many :tickets, dependent: :destroy
after_create :set_default_role
belongs_to :role, optional: true
has_one_attached :image
# has_one :flight
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  # enum role: [ employee: 0, admin: 1 ]

  validates :phone, numericality: { only_integer: true },length: { is:10 } 

  validates :name, presence: true, length: { minimum: 5 }

  validates :age, numericality: { only_integer: true }

  validates_each :name do |record, attr, value|
      record.errors.add(attr, 'must start with upper case') if value =~ /\A[[:lower:]]/
  end

    def full_name
      "#{name} #{age}"
    end

    private 
    def set_default_role
      self.update(role_id: Role.find_by(code: 'employee').id)
    end
    
end

app/helpers/airlines_helper.rb
module AirlinesHelper
end

app/helpers/airports_helper.rb
module AirportsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Alert!!!</strong> You are not authorised to access this page!!
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <%= link_to 'Airport Management', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to 'Home' ,root_path,class: "nav-link" %>
        </li>


        <% if user_signed_in? && current_user.role.code == "admin" %>

        <li class="nav-item">
          <%= link_to 'Sign out' ,destroy_user_session_path,method: :delete,class: "nav-link" %>                                                   
        </li>

        <li class="nav-item">
          <%= link_to 'Flights' ,flights_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Schedules' ,schedules_path, class: "nav-link" %>
        </li>

         <li class="nav-item">
          <%= link_to 'Tickets' ,tickets_path , class: "nav-link" %>
        </li>
        
        <li class="nav-item">
          <%= link_to 'Airports' ,airports_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Airlines' ,airport_airlines_path(current_user.airport_id), class: "nav-link" %>
        </li>

         <li class="nav-item">
          <%= link_to 'Bookings' ,bookings_path, class: "nav-link" %>
        </li>

        <% elsif user_signed_in? && current_user.role.code == "employee" %>

          <li class="nav-item">
          <%= link_to 'Sign out' ,destroy_user_session_path, method: :delete, class: "nav-link" %>                                                   
        </li>

        <li class="nav-item">
          <%= link_to 'Flights' ,flights_path, class: "nav-link" %>
        </li>
       
        <li class="nav-item">
          <%= link_to 'Schedules' ,schedules_path, class: "nav-link" %>
        </li>

        <li class="nav-item">
          <%= link_to 'Bookings' ,bookings_path, class: "nav-link" %>
        </li>

        <% else %>
   
          <li class="nav-item">
            <%= link_to 'Sign In' ,new_user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign Up' ,new_user_registration_path, class: "nav-link" %>
          </li>

           <li class="nav-item">
          <%= link_to 'Flights' ,flights_path, class: "nav-link" %>
        </li>
       
        <li class="nav-item">
          <%= link_to 'Schedules' ,schedules_path, class: "nav-link" %>
        </li>
      
     

        <% end %>

      </ul>

    <!--   <form class="d-flex" method="GET" action="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"name="query" method = "GET" >
        <button class="btn btn-success" type="submit">Search</button>
      </form>

     -->

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyDemo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>

     <%= stylesheet_pack_tag    "application", :media => "all", 'data-turbolinks-track': 'reload' %>
     <%= javascript_pack_tag "application", 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>

 
  </body>
</html>

app/views/pages/home.html.erb
<% if current_user %>

You are Logged in as: <%= current_user.email %><br />
You are <%= current_user.role.name %> <br />

<% end %>